--------------------------------------------------------------------------------
|                                                                              |
|                                                                              |
|           1 Activate/Halt System: XXXXXXX                                    |
|           2 Activate/Halt Device(s)                                          |
|           3 Set Run Type (REG/EMC): XXX                                      |
|           4 Show/Set/Clear "Continue on Error" Flag(s) for Device(s)         |
|                                                                              |
|           5 Display Device Status Table                                      |
|           6 Display Device Statistics                                        |
|                                                                              |
|           7 View HTX Error Log                                               |
|           8 View HTX Message Log                                             |
|           9 View Master Device Table (mdt)                                   |
|          10 Restart Exercisers                                               |
|                                                                              |
|          11 Go to shell command line                                         |
|                                                                              |
|                                                                              |
|    Please enter the number of the desired option:                            |
--------------------------------------------------------------------------------
|  h = help               d = refresh screen             s = shutdown          |
--------------------------------------------------------------------------------
