#!/bin/sh
#Syntax for adding a new mdt
#/usr/lpp/htx/etc/scripts/create_all_mdt_with_powermixer -help

/usr/lpp/htx/etc/scripts/create_all_mdt_with_powermixer  -mdt mdt.pm_8fd_char  -base_mdt mdt.core_wo_cpu -new_mdt mdt.core.GB   -priority 18
/usr/lpp/htx/etc/scripts/create_all_mdt_with_powermixer  -mdt mdt.pm_p8_cmp    -base_mdt mdt.bu_char -new_mdt mdt.p8_bu_hot_p17 -priority 13
/usr/lpp/htx/etc/scripts/create_all_mdt_with_powermixer  -mdt mdt.pm_p8_cmp    -base_mdt mdt.bu_char -new_mdt mdt.p8_bu_hot -priority 13
/usr/lpp/htx/etc/scripts/create_all_mdt_with_powermixer  -mdt mdt.pm_cmp  -base_mdt mdt.bu.characterization -new_mdt mdt.bu_hot -priority 10
/usr/lpp/htx/etc/scripts/create_all_mdt_with_powermixer  -mdt mdt.pm_cmp  -base_mdt mdt.bu.characterization -new_mdt mdt.bu_hot_p17 -priority 17
/usr/lpp/htx/etc/scripts/create_all_mdt_with_powermixer  -mdt mdt.pm_8fd_char  -base_mdt mdt.bu_combo_char -new_mdt mdt.bu_hot_combo_char -priority 13
# changed above line ti use pm_8fd_char instead of pm_p8_cmp.
