#!/bin/bash
# IBM_PROLOG_BEGIN_TAG
# 
# Copyright 2003,2016 IBM International Business Machines Corp.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# 		 http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
# implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# IBM_PROLOG_END_TAG


# Print the memory configure
/usr/lpp/htx/bin/hxefabricbus  /dev/ablink OTH /usr/lpp/htx/rules/reg/hxefabricbus/default.ab query_memconf >/dev/null 2>&1

# Print the mask configure
/usr/lpp/htx/bin/hxefabricbus /dev/ablink OTH /usr/lpp/htx/rules/reg/hxefabricbus/default.ab query_maskconf >/dev/null 2>&1



cat ${HTXMDT}mdt.all | create_mdt_with_devices.awk                                              > ${HTXMDT}mdt.ablink

echo "Creating mdt.ablink ..."
echo                                                                                            >> /usr/lpp/htx/mdt/mdt.ablink
echo 'ablink:'                                                                                  >> /usr/lpp/htx/mdt/mdt.ablink
echo -e '\tHE_name = "hxefabricbus"                     '     					>> /usr/lpp/htx/mdt/mdt.ablink
echo -e '\tadapt_desc = "Node to Node"                  '    					>> /usr/lpp/htx/mdt/mdt.ablink
echo -e '\tdevice_desc = "Memory BW"                    '     					>> /usr/lpp/htx/mdt/mdt.ablink
echo -e '\treg_rules = "hxefabricbus/default.ab"        '                          		>> /usr/lpp/htx/mdt/mdt.ablink
echo -e '\temc_rules = "hxefabricbus/default.ab"        '                          		>> /usr/lpp/htx/mdt/mdt.ablink
echo -e '\tcont_on_err = "NO"     			'                                       >> /usr/lpp/htx/mdt/mdt.ablink
echo                                                                                       	>> /usr/lpp/htx/mdt/mdt.ablink
ln -sf /usr/lpp/htx/mdt/mdt.ablink /usr/lpp/htx/ecg/ecg.ablink

