#!/bin/bash

# IBM_PROLOG_BEGIN_TAG
# 
# Copyright 2003,2016 IBM International Business Machines Corp.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# 		 http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
# implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# IBM_PROLOG_END_TAG


# Print the memory configure
/usr/lpp/htx/bin/hxefabricbus  /dev/ablink OTH /usr/lpp/htx/rules/reg/hxefabricbus/default.ab query_memconf >/dev/null 2>&1

proc_ver=`/usr/lpp/htx/bin/show_syscfg pvr | grep Version | awk -F: '{print $2}'`
proc_ver_dec=`printf %d $proc_ver`
P6Compatmode=`/usr/lpp/htx/bin/show_syscfg pvr | grep -i Power6Compatmode | awk -F: '{print $2}'|sed -e 's/^ *//' `

echo "Creating mdt.ab_mem ..."
if [[ $proc_ver_dec -ge 63 && $P6Compatmode = "False" ]] # Shifts for P7 & above
then
    create_my_mdt mem:memmfg 							> /usr/lpp/htx/mdt/mdt.ab_mem
else
    cat /usr/lpp/htx/mdt/mdt.mem  							> /usr/lpp/htx/mdt/mdt.ab_mem
fi

echo 											>> /usr/lpp/htx/mdt/mdt.ab_mem
echo 'ablink:'										>> /usr/lpp/htx/mdt/mdt.ab_mem
echo -e '\tHE_name = "hxefabricbus"                	'				>> /usr/lpp/htx/mdt/mdt.ab_mem
echo -e '\tadapt_desc = "Node to Node"            	'				>> /usr/lpp/htx/mdt/mdt.ab_mem
echo -e '\tdevice_desc = "Memory BW"              	'				>> /usr/lpp/htx/mdt/mdt.ab_mem
echo -e '\treg_rules = "hxefabricbus/default.ab"        '                          	>> /usr/lpp/htx/mdt/mdt.ab_mem
echo -e '\temc_rules = "hxefabricbus/default.ab"        '                          	>> /usr/lpp/htx/mdt/mdt.ab_mem
echo -e '\tcont_on_err = "NO" 	'						   	>> /usr/lpp/htx/mdt/mdt.ab_mem 	
echo 											>> /usr/lpp/htx/mdt/mdt.ab_mem
ln -sf /usr/lpp/htx/mdt/mdt.ab_mem /usr/lpp/htx/ecg/ecg.ab_mem
