#!/bin/ksh

# IBM_PROLOG_BEGIN_TAG
# 
# Copyright 2003,2016 IBM International Business Machines Corp.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# 		 http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
# implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# IBM_PROLOG_END_TAG

# Exerciser cleanup after running runsup only
# If device is in chosen mdt, run exerciser runcleanup scripts

  if [[ -n $(grep "hxepit" $1 2>/dev/null) ]]
     then echo "Cleaning Cricketstick token ring"
          ${HTXRUNCLEANUP}crick.runcleanup
  fi

  if [[ -n $(grep "hxeglx" $1 2>/dev/null) ]]
     then echo "Cleaning Galaxy ethernet"
          ${HTXRUNCLEANUP}glx.runcleanup
  fi

  if [[ -n $(grep "hxeskfp" $1 2>/dev/null) ]]
     then echo "Cleaning Honeycomb (SysKonnect) fddi"
          ${HTXRUNCLEANUP}honeycomb.runcleanup
  fi

  if [[ -n $(grep "hxesct"  $1 2>/dev/null) ]]
     then echo "Cleaning SCT environment"
          ${HTXRUNCLEANUP}sct.runcleanup
  fi


  if [[ -n $(grep "hxesky" $1 2>/dev/null) ]]
     then echo "Cleaning Skyline token ring"
          ${HTXRUNCLEANUP}skyline.runcleanup
  fi

  if [[ -n $(grep "hxecom" $1 2>/dev/null) ]]
     then echo "Cleaning hxecom "
          ${HTXRUNCLEANUP}hxecom.runcleanup
  fi

  if [[ -n $(grep "hxevmx64" $1 2>/dev/null) ]]
       then echo "Cleaning hxevmx64 "
            ${HTXRUNCLEANUP}hxevmx64.runcleanup
  fi
  
  if [[ -n $(grep "hxedfp" $1 2>/dev/null) ]]
       then echo "Cleaning hxedfp "
            ${HTXRUNCLEANUP}hxedfp.runcleanup
  fi  
  
  if [[ -n $(grep "hxesysben" $1 2>/dev/null) ]]
       then echo "Cleaning Hxesysben "
            ${HTXRUNCLEANUP}sysben.runcleanup
  fi
  
  if [[ -n $(grep "hxemmioi" $1 2>/dev/null) ]]
       then echo "Cleaning Hxemmioi "
            ${HTXRUNCLEANUP}mmioi.runcleanup
  fi

if [[ -n $(grep "hxediag" $1 2>/dev/null) ]]
       then echo "Cleaning hxediag "
            ${HTXRUNCLEANUP}hxediag.runcleanup
fi
