#!/bin/bash
# IBM_PROLOG_BEGIN_TAG
# 
# Copyright 2003,2016 IBM International Business Machines Corp.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# 		 http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
# implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# IBM_PROLOG_END_TAG


# Send SIGTERM to all the exerciser
ps -ef|grep hxe|awk '{print $2}'|xargs kill -15 >/dev/null 2>&1
# Send SIGTERM to all the supervisor and daemon components
ps -ef|grep hxs|awk '{print $2}'|xargs kill -15 >/dev/null 2>&1
# wait for all the exercisers to cleanup
sleep 5
# Send SIGTERM to all the exerciser again, if anyone is still alive
ps -ef|grep hxe|awk '{print $2}'|xargs kill -15 >/dev/null 2>&1
sleep 2
# Send SIGKILL to all the exerciser now
ps -ef|grep hxe|awk '{print $2}'|xargs kill -9 >/dev/null 2>&1
# Send SIGKILL to all the supervisor and daemon components
ps -ef|grep hxs|awk '{print $2}'|xargs kill -9 >/dev/null 2>&1

ps -ef | grep -w "/usr/lpp/htx/bin/htxd" | grep -v grep | awk '{print $2}' | xargs kill -9 >/dev/null 2>&1

# Clean IPC
for i in `ipcs -m |grep root|awk '{print $2}'`
do
echo $i
ipcrm -m $i
done
for i in `ipcs -s |grep root|awk '{print $2}'`
do
echo $i
ipcrm -s $i
done

for i in `ipcs -q |grep root|awk '{print $2}'`
do
echo $i
ipcrm -q $i
done
