#!/bin/bash
# @(#)28	1.6.4.1  src/htx/usr/lpp/htx/etc/scripts/htxlogout, htxconf, htxubuntu 12/18/13 07:09:25
#########################################################################

supvs=`ps -ef | grep hxssup | grep -v grep| wc -l `
if [ $supvs = 0 ]
then
    #Exerciser cleanup before logout time
    for file in `/bin/ls $HTXCLEANUP[a-zA-Z]*.cleanup 2>/dev/null| sort`
    do
       aa=`basename $file`
       ab=${aa%.cleanup}
       if [ $ab != "hxecom" ]
       then
	 echo "Cleaning ${aa%.cleanup} ...." 2>&1 | tee -a $HTXNoise
         . $file 2>&1 | tee -a $HTXNoise
       else
	 if [ -e "${HTX_HOME_DIR}/.build_net_ran" ]
	 then
	   "echo Cleaning ${aa%.cleanup} ...." 2>&1 | tee -a $HTXNoise
	   . $file 2>&1 | tee -a $HTXNoise
	 fi
      fi
  done

else
   echo " No cleanup scripts ran" 2>&1 | tee -a $HTXNoise

fi

# Then logout
unalias exit
exit
