#!/bin/bash

# IBM_PROLOG_BEGIN_TAG
# 
# Copyright 2003,2016 IBM International Business Machines Corp.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# 		 http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
# implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# IBM_PROLOG_END_TAG
#########################################################################

supvs=`ps -ef | grep hxssup | grep -v grep| wc -l `
if [ $supvs = 0 ]
then
    #Exerciser cleanup before logout time
    for file in `/bin/ls $HTXCLEANUP[a-zA-Z]*.cleanup 2>/dev/null| sort`
    do
       aa=`basename $file`
       ab=${aa%.cleanup}
       if [ $ab != "hxecom" ]
       then
	 echo "Cleaning ${aa%.cleanup} ...." 2>&1 | tee -a $HTXNoise
         . $file 2>&1 | tee -a $HTXNoise
       else
	 if [ -e "${HTX_HOME_DIR}/.build_net_ran" ]
	 then
	   "echo Cleaning ${aa%.cleanup} ...." 2>&1 | tee -a $HTXNoise
	   . $file 2>&1 | tee -a $HTXNoise
	 fi
      fi
  done

else
   echo " No cleanup scripts ran" 2>&1 | tee -a $HTXNoise

fi

# Then logout
unalias exit
exit
