#!/bin/sh
# @(#)19      1.3  src/htx/usr/lpp/htx/etc/scripts/runhxecom, htxconf, htxubuntu 9/24/03 10:38:53
	echo
	echo "HXECOM CONFIGURATION >>>>>>>"
	echo "Running hxecom breaks connectivity through network"
	echo "interfaces which are used for test. So if you are connected to"
	echo "machine using these interfaces, you will loose network connection."
	echo
	echo "If so you may want to run htx on console."
	echo -n "Do you wish to configure hxecom (y/n) "
	read  confirm
	while [ "$confirm" != "y" -a "$confirm" != "n" ]
 	do
		echo -n "Do you wish to configure hxecom (y/n) "
		read  confirm
	done
	if [ $confirm == "n" ];
	then
	exit
	fi
	while [ 1 ]
	do
		echo
		echo "If Interface Ipaddress is 192.168.1.2 then"
		echo "netid will be 192.168"
		echo
		echo -n "Please enter the CLASS C net id of Interface "
		read  netid 
		echo "The IP real ip addresses are "
		echo " Interface 1 $netid.1.1"
		echo " Interface 2 $netid.2.1"
		echo "The IP Virtual ip addresses are "
		echo " Interface 1 $netid.1.2"
		echo " Interface 2 $netid.2.2"
		echo
		echo " Please look for IP Addresses conflict" 
		echo -n "Are these Ip addresses OK (y/n) "
		read  confirm
		while [ "$confirm" != "y" -a "$confirm" != "n" ]
 		do
			echo -n "Are these Ip addresses OK (y/n) "
			read  confirm
		done 
		if [ $confirm == "y" ];
		then
			break
		fi
	done
	/usr/lpp/htx/etc/scripts/build_net $netid
	if [ -f /etc/hosts.hxecom ]; then
		/bin/cp /etc/hosts.hxecom /etc/hosts
	else
		/bin/cp /etc/hosts /etc/hosts.hxecom
	fi
	echo "$netid.1.1	150net236" >> /etc/hosts 
	echo "$netid.2.1	150net17" >> /etc/hosts
	cp /usr/lpp/htx/mdt/mdt.all /usr/lpp/htx/etc/scripts/mdt.all.hxecom
	cat /usr/lpp/htx/mdt/mdt.net >> /usr/lpp/htx/mdt/mdt.all 
