include ../../../htx.mk

TARGET= \
	default hxefpscr.readme

.PHONY: all clean

all: ${TARGET}
	${MKDIR} ${REGRULES}/hxefpscr/
	${CP} ${TARGET} ${REGRULES}/hxefpscr/ 

clean:
	${RM} -rf ${REGRULES}/hxefpscr/*
