#!/bin/bash

# @(#)14        1.3  src/htx/usr/lpp/htx/etc/scripts/create_mdt_ab, exer_ablink, htxltsbml 1/1/09 23:47:10

# Print the memory configure
/usr/lpp/htx/bin/hxefabricbus  /dev/ablink OTH /usr/lpp/htx/rules/reg/hxefabricbus/default.ab query_memconf >/dev/null 2>&1

# Print the mask configure
/usr/lpp/htx/bin/hxefabricbus /dev/ablink OTH /usr/lpp/htx/rules/reg/hxefabricbus/default.ab query_maskconf >/dev/null 2>&1



cat ${HTXMDT}mdt.all | create_mdt_with_devices.awk                                              > ${HTXMDT}mdt.ablink

echo "Creating mdt.ablink ..."
echo                                                                                            >> /usr/lpp/htx/mdt/mdt.ablink
echo 'ablink:'                                                                                  >> /usr/lpp/htx/mdt/mdt.ablink
echo -e '\tHE_name = "hxefabricbus"                     '     					>> /usr/lpp/htx/mdt/mdt.ablink
echo -e '\tadapt_desc = "Node to Node"                  '    					>> /usr/lpp/htx/mdt/mdt.ablink
echo -e '\tdevice_desc = "Memory BW"                    '     					>> /usr/lpp/htx/mdt/mdt.ablink
echo -e '\treg_rules = "hxefabricbus/default.ab"        '                          		>> /usr/lpp/htx/mdt/mdt.ablink
echo -e '\temc_rules = "hxefabricbus/default.ab"        '                          		>> /usr/lpp/htx/mdt/mdt.ablink
echo -e '\tcont_on_err = "NO"     			'                                       >> /usr/lpp/htx/mdt/mdt.ablink
echo                                                                                       	>> /usr/lpp/htx/mdt/mdt.ablink
ln -sf /usr/lpp/htx/mdt/mdt.ablink /usr/lpp/htx/ecg/ecg.ablink

