#!/bin/sh

# @(#)41  1.1  src/htx/usr/lpp/htx/etc/scripts/start_shift, htxconf, htxubuntu 3/28/13 05:07:37

# Check for mdt name.
if [ -z $1 ]
then
        echo "mdt name missing."
        echo "Usage: $0 <mdt-name>"
        exit
fi
export MDT_NAME=$1
export MDT=/usr/lpp/htx/mdt/$MDT_NAME

# Test status values.
export RUNNING=1
export ERROR=2

# SCOM mapped files.
mkdir -p /tmp/shift

export STATUS_FILE=/tmp/shift/status
export RUN_TIME_FILE=/tmp/shift/run_time
export LAST_UPDATE_TIME_FILE=/tmp/shift/last_update_time
export MDT_NAME_FILE=/tmp/shift/mdt_name

# Update SCOM mapped files with initial values.
# Exer cycle count file will be updated later.
echo 0 > $STATUS_FILE
echo 0 > $RUN_TIME_FILE
echo 0 > $LAST_UPDATE_TIME_FILE
echo $MDT_NAME > $MDT_NAME_FILE

# Log files
export ERROR_LOG_FILE=/tmp/shift/error.txt
export PROGRESS_LOG_FILE=/tmp/shift/progress.txt
touch $ERROR_LOG_FILE $PROGRESS_LOG_FILE

# Setup LPAR parameters.
echo 1 > /proc/sys/kernel/print-fatal-signals
echo /tmp/core.%e.%p > /proc/sys/kernel/core_pattern

# Export SHIFT_LOG_DONE_FILE variable. It holds path for file 
# which is used to inform completion of shift log collection.
# Remove SHIFT_LOG_DONE_FILE, if present from previous run.
export SHIFT_LOG_DONE_FILE=/tmp/shift/shift_log_done
rm -f $SHIFT_LOG_DONE_FILE

echo 
echo "Starting STX on LPAR `hostname` with MDT $MDT"; echo
/start_stx_lpar $MDT_NAME 2>&1 | tee $PROGRESS_LOG_FILE 

