include ../../../htx.mk
TARGET = \
            hxefabricbus.readme \
            default.ab \
            default.xyz

.PHONY: all clean

all: ${TARGET}
	${MKDIR} ${REGRULES}/hxefabricbus/
	${CP} ${TARGET} ${REGRULES}/hxefabricbus/ 

clean:
	${RM} -rf ${REGRULES}/hxefabricbus/* 
