#!/bin/bash

set -e

case "$1" in
	remove)
		[[ -h /bin/ver ]] && rm -rf /bin/ver 2>/dev/null
		[[ -h /bin/htxcmdline ]] && rm -rf /bin/htxcmdline 2>/dev/null
		[[ -d /usr/lpp/htx ]] &&  rm -rf /usr/lpp/htx 2>/dev/null
		[[ -s /bin/set_linux_nets ]] && rm -rf /bin/set_linux_nets 2>/dev/null
		[[ -s /etc/cpdir ]] && rm -rf /etc/cpdir 2>/dev/null
		[[ -s /etc/gethelp ]] && rm -rf /etc/gethelp 2>/dev/null
		[[ -s /etc/gethtx ]] && rm -rf /etc/gethtx 2>/dev/null
		[[ -s /etc/getnet ]] && rm -rf /etc/getnet 2>/dev/null
		[[ -s /etc/gettools ]] && rm -rf /etc/gettools 2>/dev/null
		[[ -s /etc/tping ]] && rm -rf /etc/tping 2>/dev/null
		if id htx > /dev/null 2>&1 ; then userdel -f htx 2>/dev/null; fi
		if id -g htx > /dev/null 2>&1 ; then groupmod -g 999 htx 2>/dev/null; fi
		if id -g htx > /dev/null 2>&1 ; then groupdel htx 2>/dev/null; fi
		rm -rf /etc/init.d/htx.d 2>/dev/null
	;;

	purge|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
		echo $1
	;;

	*)
		echo "postrm called with unknown argument \`\$1'" >&2
		exit 0
	;;
esac

exit 0
