#!/bin/bash

set -e

case "$1" in
	remove)
		/etc/init.d/htx.d stop >/dev/null 2>&1
		update-rc.d -f htx.d remove
	;;

	purge|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
		echo $1
	;;

	*)
		echo "prerm called with unknown argument \`\$1'" >&2
		exit 0
	;;
esac


