include ../../../htx.mk

TARGET= default default.capi

.PHONY: all clean

all: ${TARGET}
	${MKDIR} ${REGRULES}/hxecorsa/
	${CP} ${TARGET} ${REGRULES}/hxecorsa/ 

clean:
	${RM} -rf ${REGRULES}/hxecorsa/* 
